const imageLoaders={};
async function loadImage(key,file){if(!file)return;if(!/^image\/(png|jpeg|webp)$/i.test(file.type)&&!(!file.type&&/\.(png|jpe?g|webp)$/i.test(file.name))){status('请选择 PNG、JPEG 或 WebP 图片文件。');return}if(busy){status('正在导出，请完成后再导入图片。');return}return imageLoaders[key](file)}
const $=id=>document.getElementById(id),states={},defs=[['strength','整体强度',0,100,70],['naturalness','自然度',0,100,70],['fidelity','产品本色保护',0,100,70],['warmth','冷 ← 冷暖 → 暖',-25,25,0],['tint','绿 ← 色偏 → 洋红',-25,25,0],['saturation','饱和度',-40,40,0],['light','明暗',-25,25,0],['contrast','对比度',-30,30,0]];let scheduled=false,busy=false,revision=0,interactiveRendering=false,interactionTimer=null,castCorrection={strength:0,a:[0,0,0],b:[0,0,0],meanA:0,meanB:0,severity:0,label:'尚未分析参考光感',summary:''},clarityCorrection={strength:0,anchors:[20,55,88],delta:[0,0,0],local:0,preserveHighlights:true,label:'尚未分析通透度'};
function requestInteractiveRender(){interactiveRendering=true;clearTimeout(interactionTimer);render();interactionTimer=setTimeout(finishInteractiveRender,140)}
function finishInteractiveRender(){clearTimeout(interactionTimer);interactionTimer=null;if(!interactiveRendering)return;interactiveRendering=false;render()}
for(const [id,name,min,max,value]of defs){let label=document.createElement('label');label.className='control';label.innerHTML=`<span>${name}<output id="${id}Value">${value}</output></span><input id="${id}" type="range" min="${min}" max="${max}" value="${value}">`;$('controls').append(label);$(id).oninput=()=>{revision++;$(id+'Value').value=$(id).value;requestInteractiveRender()};$(id).onchange=finishInteractiveRender}
const parameters=()=>({...Object.fromEntries(defs.map(([id])=>[id,+$(id).value])),cast:{strength:castCorrection.strength,a:[...castCorrection.a],b:[...castCorrection.b]},clarity:{strength:clarityCorrection.strength,anchors:[...clarityCorrection.anchors],delta:[...clarityCorrection.delta],local:clarityCorrection.local,preserveHighlights:clarityCorrection.preserveHighlights}});
function setValues(values,interactive=false){for(const[id,v]of Object.entries(values)){$(id).value=v;$(id+'Value').value=$(id).value}revision++;interactive?requestInteractiveRender():render()}
function status(t){$('status').textContent=t}
function resetCastCorrection(){castCorrection={strength:0,a:[0,0,0],b:[0,0,0],meanA:0,meanB:0,severity:0,label:'尚未分析参考光感',summary:''};if($('castStrength')){$('castStrength').value=0;$('castStrengthValue').value=0;$('castStatus').textContent=castCorrection.label;$('castStrengthWrap').hidden=true}render()}
function resetClarityCorrection(){clarityCorrection={strength:0,anchors:[20,55,88],delta:[0,0,0],local:0,preserveHighlights:true,label:'尚未分析通透度'};if($('clarityStrength')){$('clarityStrength').value=0;$('clarityStrengthValue').value=0;$('clarityStatus').textContent=clarityCorrection.label;$('clarityControls').hidden=true}render()}
function resetEnhancements(){resetCastCorrection();resetClarityCorrection()}

function repaint(key){const s=states[key],ctx=$(key).getContext('2d');ctx.putImageData(s.data,0,0);let overlay=ctx.createImageData(s.w,s.h);for(let i=0;i<s.mask.length;i++){let v=s.mask[i];if(v){overlay.data.set(v===1?[30,180,110,110]:[240,65,65,120],i*4)}}let c=document.createElement('canvas');c.width=s.w;c.height=s.h;c.getContext('2d').putImageData(overlay,0,0);ctx.drawImage(c,0,0)}
for(const key of ['target','reference']){
$(key+'File').onchange=async e=>{const input=e.target;let file=input.files[0];input.value='';if(file)await loadImage(key,file)};
async function loadThisImage(file){if(!file)return;const ticket=Symbol();$(key).loadTicket=ticket;try{let img=await createImageBitmap(file,{imageOrientation:'from-image'});if($(key).loadTicket!==ticket){img.close();return}if(img.width*img.height>50000000){img.close();throw Error('图片超过 5000 万像素，请缩小后上传。')}let scale=Math.min(1,1200/Math.max(img.width,img.height)),c=$(key);c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);const fastScale=Math.min(1,560/Math.max(c.width,c.height)),fastCanvas=document.createElement('canvas');fastCanvas.width=Math.max(1,Math.round(c.width*fastScale));fastCanvas.height=Math.max(1,Math.round(c.height*fastScale));fastCanvas.getContext('2d').drawImage(c,0,0,fastCanvas.width,fastCanvas.height);states[key]?.image.close();states[key]={image:img,name:file.name,w:c.width,h:c.height,data:c.getContext('2d').getImageData(0,0,c.width,c.height),fast:{w:fastCanvas.width,h:fastCanvas.height,data:fastCanvas.getContext('2d').getImageData(0,0,fastCanvas.width,fastCanvas.height)},mask:new Uint8Array(c.width*c.height)};$(key+'Empty').hidden=true;revision++;resetEnhancements();if(key==='target'){setValues(Object.fromEntries(defs.map(([id,,, ,v])=>[id,v])));$('dimensions').textContent=`原图 ${img.width} × ${img.height} · 预览 ${c.width} × ${c.height} · 导出保留原尺寸及透明度`}$('match').disabled=!(states.target&&states.reference);$('export').disabled=!states.target;$('openPreview').disabled=!states.target;$('params').disabled=!states.target;status('图片已加载。可直接初调，也可以先涂选对应的墙面或地面。');render()}catch(err){if($(key).loadTicket===ticket)status('加载失败：'+err.message)}};
imageLoaders[key]=loadThisImage;
$(key+'Clear').onclick=()=>{if(!states[key])return;states[key].mask.fill(0);repaint(key);status('选区已清空。点击重新取样以更新调整。')};let drawing=false,last=null;
const paint=e=>{if(!drawing||!states[key])return;let s=states[key],rect=$(key).getBoundingClientRect(),x=(e.clientX-rect.left)*s.w/rect.width,y=(e.clientY-rect.top)*s.h/rect.height,r=+$('brush').value*s.w/rect.width/2,mode=$(key+'Mode').value,v=mode==='include'?1:mode==='exclude'?2:0;let old=last||[x,y],dist=Math.hypot(x-old[0],y-old[1]),steps=Math.max(1,Math.ceil(dist/Math.max(1,r/2)));for(let k=0;k<=steps;k++){let cx=old[0]+(x-old[0])*k/steps,cy=old[1]+(y-old[1])*k/steps;for(let yy=Math.max(0,Math.floor(cy-r));yy<Math.min(s.h,cy+r);yy++)for(let xx=Math.max(0,Math.floor(cx-r));xx<Math.min(s.w,cx+r);xx++)if((xx-cx)**2+(yy-cy)**2<=r*r)s.mask[yy*s.w+xx]=v}last=[x,y];repaint(key)};
$(key).onpointerdown=e=>{drawing=true;last=null;$(key).setPointerCapture(e.pointerId);paint(e)};$(key).onpointermove=paint;$(key).onpointerup=$(key).onpointercancel=()=>{drawing=false;last=null};
}
$('match').onclick=()=>{resetCastCorrection();resetClarityCorrection();try{const a=SceneColor.stats(states.target.data.data,states.target.mask),b=SceneColor.stats(states.reference.data.data,states.reference.mask);setValues({strength:70,warmth:Math.round(SceneColor.clamp(b.b-a.b,-18,18)),tint:Math.round(SceneColor.clamp((b.a-a.a)*.7,-8,8)),light:Math.round(SceneColor.clamp(b.l-a.l,-15,15)),saturation:0,contrast:0});status(`初调完成：目标 ${a.count}、参考 ${b.count} 个取样点。可在效果预览中继续去偏色或优化通透度。`)}catch(e){status(e.message)}};
function render(){if(scheduled||!states.target)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;const state=states.target,s=interactiveRendering?state.fast:state,c=$('output'),p=parameters();c.width=s.w;c.height=s.h;let ctx=c.getContext('2d'),out=ctx.createImageData(s.w,s.h);SceneColor.transform(s.data.data,out.data,p);SceneColor.clarity(out.data,s.w,s.h,p.clarity);ctx.putImageData(out,0,0);const report=SceneColor.qualityReport(s.data.data,out.data);c.dataset.quality=JSON.stringify(report);c.dataset.previewMode=interactiveRendering?'fast':'full';let before=$('before');before.width=s.w;before.height=s.h;before.getContext('2d').putImageData(s.data,0,0);compare();syncPreview()})}
function compare(){$('before').style.clipPath=`inset(0 ${100-$('compare').value}% 0 0)`}$('compare').oninput=compare;
$('reset').onclick=()=>{resetCastCorrection();resetClarityCorrection();setValues(Object.fromEntries(defs.map(([id,,,,v])=>[id,v])))};
let importTarget='target';
function selectImportTarget(key){importTarget=key;for(const k of ['target','reference']){$(k).parentElement.classList.toggle('is-import-target',k===key);$('importHint-'+k).textContent=k===key?'当前粘贴目标 · Ctrl+V 粘贴图片，或拖入图片':'点击此区域后 Ctrl+V 粘贴，或直接拖入图片'}}
function importFiles(key,files){const items=Array.from(files||[]);if(!items.length){status('请拖入或粘贴图片文件，暂不支持图片网址。');return}if(items.length!==1){status('每个区域请一次导入一张图片。');return}return loadImage(key,items[0])}
for(const key of ['target','reference']){
const stage=$(key).parentElement;stage.tabIndex=0;stage.setAttribute('aria-label',(key==='target'?'目标场景':'风格参考')+'，支持拖入图片或按 Ctrl+V 粘贴');const hint=document.createElement('small');hint.className='import-hint';hint.id='importHint-'+key;hint.textContent='点击此区域后 Ctrl+V 粘贴，或直接拖入图片';stage.after(hint);
stage.addEventListener('focus',()=>selectImportTarget(key));stage.addEventListener('pointerdown',()=>{selectImportTarget(key);stage.focus({preventScroll:true})},true);
stage.addEventListener('keydown',e=>{if(e.target===stage&&(e.key==='Enter'||e.key===' ')){e.preventDefault();$(key+'File').click()}});
$(key+'File').addEventListener('focus',()=>selectImportTarget(key));
let dragDepth=0;stage.addEventListener('dragenter',e=>{e.preventDefault();dragDepth++;stage.classList.add('is-dragover')});stage.addEventListener('dragover',e=>{e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect='copy'});stage.addEventListener('dragleave',()=>{dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)stage.classList.remove('is-dragover')});stage.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();dragDepth=0;stage.classList.remove('is-dragover');selectImportTarget(key);if(!$('previewDialog').open)importFiles(key,e.dataTransfer?.files)});
}
document.addEventListener('dragover',e=>{if(Array.from(e.dataTransfer?.types||[]).includes('Files'))e.preventDefault()});
document.addEventListener('drop',e=>{if(Array.from(e.dataTransfer?.types||[]).includes('Files'))e.preventDefault()});
document.addEventListener('paste',e=>{if($('previewDialog').open||e.target.closest?.('textarea,[contenteditable="true"],input:not([type="range"]):not([type="file"])'))return;const data=e.clipboardData;if(!data)return;const files=Array.from(data.files||[]);if(!files.length)for(const item of Array.from(data.items||[])){if(item.kind==='file'){const file=item.getAsFile();if(file)files.push(file)}}if(!files.length)return;e.preventDefault();selectImportTarget(importTarget);importFiles(importTarget,files)});
function download(blob,name){let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('params').onclick=()=>download(new Blob([JSON.stringify({version:1,target:states.target.name,reference:states.reference?.name,parameters:parameters(),note:'参数作用于全图；选区仅用于估计。'},null,2)],{type:'application/json'}),'scene-tone-settings.json');
$('export').onclick=async()=>{
if(busy||!states.target)return;busy=true;$('export').disabled=true;let s=states.target,p=parameters();
try{
let c=document.createElement('canvas');c.width=s.image.width;c.height=s.image.height;let ctx=c.getContext('2d');ctx.drawImage(s.image,0,0);
for(let y=0;y<c.height;y+=64){let h=Math.min(64,c.height-y),data=ctx.getImageData(0,y,c.width,h),out=ctx.createImageData(c.width,h);SceneColor.transform(data.data,out.data,p);ctx.putImageData(out,0,y);status(`正在导出 ${Math.round((y+h)/c.height*80)}%…`);await new Promise(r=>setTimeout(r,0))}
if(p.clarity?.strength&&p.clarity.local){const result=document.createElement('canvas');result.width=c.width;result.height=c.height;const resultCtx=result.getContext('2d'),radius=Math.max(2,Math.round(Math.min(c.width,c.height)/85));for(let y=0;y<c.height;y+=64){const h=Math.min(64,c.height-y),top=Math.max(0,y-radius),bottom=Math.min(c.height,y+h+radius),data=ctx.getImageData(0,top,c.width,bottom-top);SceneColor.clarity(data.data,c.width,bottom-top,p.clarity,radius);resultCtx.putImageData(data,0,top,0,y-top,c.width,h);status(`正在优化通透度 ${80+Math.round((y+h)/c.height*20)}%…`);await new Promise(r=>setTimeout(r,0))}c=result}
let blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw Error('浏览器无法编码此尺寸，请缩小图片。');download(blob,s.name.replace(/\.[^.]+$/,'')+'-调色.png');status('原尺寸 PNG 已生成，请查看浏览器下载。')
}catch(e){status('导出失败：'+e.message)}finally{busy=false;$('export').disabled=!states.target}
};
