(function(root){
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function rgbLab(r,g,b){let c=[r,g,b].map(v=>{v/=255;return v>.04045?((v+.055)/1.055)**2.4:v/12.92});[r,g,b]=c;let x=(r*.4124564+g*.3575761+b*.1804375)/.95047,y=r*.2126729+g*.7151522+b*.072175,z=(r*.0193339+g*.119192+b*.9503041)/1.08883;let f=t=>t>.0088564517?Math.cbrt(t):7.787037*t+16/116;return [116*f(y)-16,500*(f(x)-f(y)),200*(f(y)-f(z))]}
function gamutCompress(rgb){const lo=Math.min(...rgb),hi=Math.max(...rgb);if(lo>=0&&hi<=1)return rgb;const y=clamp(rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722,0,1);let scale=1;for(const v of rgb){const d=v-y;if(d>0)scale=Math.min(scale,(1-y)/d);else if(d<0)scale=Math.min(scale,-y/d)}scale=clamp(scale,0,1);return rgb.map(v=>y+(v-y)*scale)}
function labRgb(l,a,b){let y=(l+16)/116,x=y+a/500,z=y-b/200;let f=t=>t**3>.0088564517?t**3:(t-16/116)/7.787037;x=.95047*f(x);y=f(y);z=1.08883*f(z);const linear=gamutCompress([3.2404542*x-1.5371385*y-.4985314*z,-.969266*x+1.8760108*y+.041556*z,.0556434*x-.2040259*y+1.0572252*z]);return linear.map(v=>255*(v>.0031308?1.055*v**(1/2.4)-.055:12.92*v))}
function smoothstep(a,b,v){const t=clamp((v-a)/(b-a),0,1);return t*t*(3-2*t)}
function softLimit(value,min,max){if(value<min)return min-(min-value)/(1+(min-value)/6);if(value>max)return max+(value-max)/(1+(value-max)/6);return value}
function stats(data,mask){let manual=mask.some(v=>v===1),all=[],neutral=[];let step=Math.max(1,Math.floor(mask.length/80000));for(let i=0;i<mask.length;i+=step){if(data[i*4+3]<240||mask[i]===2||(manual&&mask[i]!==1))continue;let lab=rgbLab(...data.slice(i*4,i*4+3));if(lab[0]<10||lab[0]>95)continue;all.push(lab);if(Math.hypot(lab[1],lab[2])<25)neutral.push(lab)}let rows=!manual&&neutral.length>=100?neutral:all;if(rows.length<20)throw Error('有效取样不足：请扩大选区，并避开纯白高光、深黑阴影或透明区域。');let median=a=>{a.sort((a,b)=>a-b);return a[Math.floor(a.length/2)]};return {l:median(rows.map(r=>r[0])),a:median(rows.map(r=>r[1])),b:median(rows.map(r=>r[2])),count:rows.length,manual}}
function bandStats(data,mask){let manual=mask?.some(v=>v===1),bins=[[],[],[]],step=Math.max(1,Math.floor(data.length/4/90000));for(let i=0;i<data.length/4;i+=step){if(data[i*4+3]<240||mask?.[i]===2||(manual&&mask[i]!==1))continue;let lab=rgbLab(data[i*4],data[i*4+1],data[i*4+2]),chroma=Math.hypot(lab[1],lab[2]);if(lab[0]<10||lab[0]>96||chroma>45)continue;bins[lab[0]<40?0:lab[0]<72?1:2].push({a:lab[1],b:lab[2],c:chroma})}return bins.map(rows=>{rows.sort((x,y)=>x.c-y.c);rows=rows.slice(0,Math.max(1,Math.ceil(rows.length*.7)));const median=key=>{const values=rows.map(r=>r[key]).sort((a,b)=>a-b);return values[Math.floor(values.length/2)]};return rows.length>=20?{a:median('a'),b:median('b'),count:rows.length}:null})}
function castProfile(target,targetMask,reference,referenceMask){const t=bandStats(target,targetMask),r=bandStats(reference,referenceMask),allT=stats(target,targetMask),allR=stats(reference,referenceMask),a=[],b=[];for(let i=0;i<3;i++){a[i]=clamp((r[i]?.a??allR.a)-(t[i]?.a??allT.a),-24,24);b[i]=clamp((r[i]?.b??allR.b)-(t[i]?.b??allT.b),-20,20)}for(let i=0;i<3;i++){if(i===1){a[i]=clamp((a[0]+2*a[1]+a[2])/4,-24,24);b[i]=clamp((b[0]+2*b[1]+b[2])/4,-20,20)}}const severity=Math.max(...a.map(Math.abs),...b.map(v=>Math.abs(v)*.7)),meanA=(a[0]+a[1]+a[2])/3,meanB=(b[0]+b[1]+b[2])/3;let label=severity<2?'参考图与目标图的环境偏色接近':Math.abs(meanA)>=Math.abs(meanB)?(meanA<0?'参考图更偏绿':'参考图更偏洋红'):(meanB<0?'参考图更偏蓝':'参考图更偏黄');return {a,b,meanA,meanB,severity,label,summary:`黄蓝 ${meanB>=0?'+':''}${meanB.toFixed(1)} · 绿洋红 ${meanA>=0?'+':''}${meanA.toFixed(1)}`,strength:severity>=10?100:severity>=5?85:65}}
function bandValue(values,l){if(l<=40)return values[0];if(l<72)return values[0]+(values[1]-values[0])*(l-40)/32;return values[1]+(values[2]-values[1])*Math.min(1,(l-72)/24)}
function lightPercentiles(data){const values=[],step=Math.max(1,Math.floor(data.length/4/100000));for(let i=0;i<data.length/4;i+=step){if(data[i*4+3]<240)continue;const l=rgbLab(data[i*4],data[i*4+1],data[i*4+2])[0];if(l>3&&l<99)values.push(l)}if(values.length<30)throw Error('有效明暗信息不足。');values.sort((a,b)=>a-b);const q=p=>values[Math.floor((values.length-1)*p)];return [q(.06),q(.5),q(.94)]}
function clarityProfile(target,reference){const t=lightPercentiles(target),r=lightPercentiles(reference),delta=t.map((v,i)=>clamp(r[i]-v,i===1?-8:-10,i===1?8:10)),targetRange=t[2]-t[0],referenceRange=r[2]-r[0],spread=referenceRange-targetRange;return {anchors:t,delta,strength:spread>5?90:spread>1?80:70,local:clamp(.18+spread/70,.12,.38),preserveHighlights:true,label:spread>3?'参考图明暗层次更开阔':'已匹配参考图的黑白场与中间调'}}
function toneDelta(profile,l){const x=[0,...profile.anchors,100],y=[0,...profile.delta,0];let n=1;while(n<x.length-1&&l>x[n])n++;const t=clamp((l-x[n-1])/Math.max(.001,x[n]-x[n-1]),0,1),smooth=t*t*(3-2*t);return y[n-1]+(y[n]-y[n-1])*smooth}
function clarity(data,w,h,profile,radiusOverride){if(!profile?.strength||!profile.local)return;const amount=profile.local*profile.strength/100,r=radiusOverride??Math.max(2,Math.round(Math.min(w,h)/85)),lum=new Float32Array(w*h),tmp=new Float32Array(w*h),blurred=new Float32Array(w*h);for(let i=0;i<lum.length;i++)lum[i]=data[i*4]*.2126+data[i*4+1]*.7152+data[i*4+2]*.0722;for(let y=0;y<h;y++){let sum=0;for(let x=-r;x<=r;x++)sum+=lum[y*w+clamp(x,0,w-1)];for(let x=0;x<w;x++){tmp[y*w+x]=sum/(2*r+1);sum-=lum[y*w+clamp(x-r,0,w-1)];sum+=lum[y*w+clamp(x+r+1,0,w-1)]}}for(let x=0;x<w;x++){let sum=0;for(let y=-r;y<=r;y++)sum+=tmp[clamp(y,0,h-1)*w+x];for(let y=0;y<h;y++){blurred[y*w+x]=sum/(2*r+1);sum-=tmp[clamp(y-r,0,h-1)*w+x];sum+=tmp[clamp(y+r+1,0,h-1)*w+x]}}for(let i=0;i<lum.length;i++){const v=lum[i]/255,protect=4*v*(1-v),d=clamp((lum[i]-blurred[i])*amount*protect,-12,12);data[i*4]=clamp(data[i*4]+d,0,255);data[i*4+1]=clamp(data[i*4+1]+d,0,255);data[i*4+2]=clamp(data[i*4+2]+d,0,255)}}
function transform(src,dst,p,start=0,end=src.length){const strength=(p.strength||0)/100,castStrength=(p.cast?.strength||0)/100,clarityStrength=(p.clarity?.strength||0)/100,fidelity=clamp((p.fidelity??70)/100,0,1),naturalness=clamp((p.naturalness??70)/100,0,1);for(let i=start;i<end;i+=4){if(strength===0&&castStrength===0&&clarityStrength===0){dst.set(src.subarray(i,i+4),i);continue}const original=rgbLab(src[i],src[i+1],src[i+2]);let [l,a,b]=original,chroma=Math.hypot(a,b),colorProtect=1-fidelity*.72*smoothstep(18,58,chroma);if(castStrength){const neutralProtect=clamp(1-Math.max(0,chroma-14)/55,.25,1),apply=neutralProtect+(1-neutralProtect)*(1-fidelity)*.35;a+=bandValue(p.cast.a,l)*castStrength*apply;b+=bandValue(p.cast.b,l)*castStrength*apply}let nl=softLimit(l+strength*((p.light||0)*4*(l/100)*(1-l/100)+(l-50)*(p.contrast||0)/100),1,99);if(clarityStrength){let d=toneDelta(p.clarity,nl)*clarityStrength;if(p.clarity.preserveHighlights&&nl>86)d*=Math.max(0,(100-nl)/14);nl=softLimit(nl+d,1,99)}const sat=1+strength*(p.saturation||0)/100*colorProtect;let na=(a+strength*(p.tint||0)*colorProtect)*sat,nb=(b+strength*(p.warmth||0)*colorProtect)*sat;const dl=nl-original[0],da=na-original[1],db=nb-original[2],delta=Math.hypot(dl,da,db),limit=30-16*naturalness;if(delta>limit){const allowed=limit+(delta-limit)*(1-naturalness*.78),scale=allowed/delta;nl=original[0]+dl*scale;na=original[1]+da*scale;nb=original[2]+db*scale}const rgb=labRgb(nl,na,nb);dst[i]=rgb[0];dst[i+1]=rgb[1];dst[i+2]=rgb[2];dst[i+3]=src[i+3]}}
function qualityReport(src,dst){let clipped=0,changed=0,total=0,delta=0;const step=Math.max(4,Math.floor(src.length/400000/4)*4);for(let i=0;i<src.length;i+=step){if(src[i+3]<240)continue;total++;if(dst[i]<=1||dst[i]>=254||dst[i+1]<=1||dst[i+1]>=254||dst[i+2]<=1||dst[i+2]>=254)clipped++;const a=rgbLab(src[i],src[i+1],src[i+2]),b=rgbLab(dst[i],dst[i+1],dst[i+2]),d=Math.hypot(b[0]-a[0],b[1]-a[1],b[2]-a[2]);delta+=d;if(d>12)changed++}return {clipped:total?clipped/total:0,strongChange:total?changed/total:0,averageDelta:total?delta/total:0,label:!total?'无法分析':clipped/total>.08?'高光或高饱和区域仍有裁切风险':changed/total>.18?'调整幅度较大，建议提高自然度':'颜色处于安全范围'}}
root.SceneColor={rgbLab,labRgb,gamutCompress,stats,castProfile,clarityProfile,clarity,transform,qualityReport,clamp};if(typeof module!=='undefined')module.exports=root.SceneColor;
})(typeof globalThis!=='undefined'?globalThis:this);
